### ISSUE TITLE
Indium conflicts with resource packs.

### ISSUE THREAD

**Issue by respectablenoob-source** [comp500/Indium#95] opened 2021-12-09 21:20 UTC
Indium conflicts with rexxstone's resource pack when modifying it to use clean redstone, the redstone beceomes  big red and black square. Also creates conflicts with other blockstate altering textures.

**Comment by comp500** [comment] 2021-12-09 22:53
Does this occur with only Sodium, no Indium? Please provide the resource pack that you used, and what it should look like, so I can test it myself.

**Comment by respectablenoob-source** [comment] 2021-12-09 23:44
Disabing indium fixes the issue. I am using [rexxstones resource pack](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbXZkOXd4dnJtVHhsUm5oVGVtVHpHNDhxX21rd3xBQ3Jtc0ttcTlTTjFLZUV4UTE0WFFfZ3Z6ZWlDeDZVeWZnUndCcVctemIwNU9CbGE5Y19hTkxtQjdKeUplVF9ENk9PYWFfOXo1Wk9ZNWtWSDh0UzVkRlZ5Q3FZQk14UW1tT2lMRndMQ01XUXBJNmxPYXJhM1Biaw&q=https%3A%2F%2Fwww.planetminecraft.com%2Ftexture-pack%2Fredstone-tweaks%2F)

Default values of the pack work with indium, however when changing redstone texture using this guide:https://www.youtube.com/watch?v=mHzThetR9l0
Indium breaks the clean redstone.
What it looks like:
![2021-12-10_08 00 21](https://user-images.githubusercontent.com/74622770/145492564-be26862c-43bb-4091-9e14-06a14b52a89f.png)
What it should look like:

![2021-12-10_12 43 32](https://user-images.githubusercontent.com/74622770/145492987-33191964-d3a6-48fc-87f5-8ea739d4e30f.png)

**Comment by comp500** [comment] 2021-12-10 00:25
![image](https://user-images.githubusercontent.com/1138417/145496432-8316699e-734a-4d7f-ba40-4bdfd15433aa.png)

This appears to work fine for me. Have you set up the pack correctly? What versions of Indium and other mods are you using?

**Comment by respectablenoob-source** [comment] 2021-12-10 00:29
I should probably change version, just realised I was using alpha. Will update you.

**Comment by respectablenoob-source** [comment] 2021-12-10 00:31
What version of indium are you using? There is only an alpha build for indium 1.18. Do I have to build it from source?

**Comment by comp500** [comment] 2021-12-10 00:32
I'm using the released alpha versions of Sodium and Indium for 1.18; 0.4.0-alpha5 and 1.0.2-alpha1 respectively.

**Comment by respectablenoob-source** [comment] 2021-12-10 00:37
Thanks for your help, I was using the build produced from running the gradlew.bat

**Comment by comp500** [comment] 2021-12-11 20:41
Did you manage to fix the issue? or does it still occur using the released versions?

**Comment by comp500** [comment] 2022-01-05 16:48
Closing (unable to reproduce issue)

**Closed as completed by comp500** 2022-01-05 16:48 UTC
