### ISSUE TITLE
game crashes evry time i join a world 

### ISSUE THREAD

**Issue by DJkitty2** [comp500/Indium#332] opened 2024-08-14 00:44 UTC
### Confirmation

- [ ] I have tested the bug without Sodium and Indium.
- [x] I have kept all my mods up to date.

### Mod Version

1.0.34+mc1.21

### Minecraft Version

1.21

### Attach latest.log

https://mclo.gs/wpHNrZP

### Attach Crash Report

[crash-2024-08-13_20.39.43-client.txt](https://github.com/user-attachments/files/16606514/crash-2024-08-13_20.39.43-client.txt)

### Additional Information

in a mod pack I made
[Best mc 1.21 1.0.0.zip](https://github.com/user-attachments/files/16606523/Best.mc.1.21.1.0.0.zip)

**Comment by ash-development** [comment] 2024-08-14 02:36
duplicate of #324 :P

**Comment by DJkitty2** [comment] 2024-08-14 14:28
thanks

**Closed as completed** 2024-08-14 14:28 UTC
Labels: bug
