### ISSUE TITLE
BufferBuilder not started (GUI crash / FTB Quests)

### ISSUE THREAD

**Issue by chorbintime** [comp500/Indium#186] opened 2023-04-06 08:39 UTC
Crash while adding new quests to FTBQuests. No concrete steps to reproduce the issue. Seems to happen when the screen to add an item as a task is opening, but it doesn't happen every time.
https://mclo.gs/rISII5Z
https://mclo.gs/0BptwM1

**Comment by comp500** [comment] 2023-04-06 17:10
Likely to be the same issue as #166

**Comment by comp500** [comment] 2023-06-04 13:33
Duplicate of https://github.com/comp500/Indium/issues/166

**Closed as not planned by comp500** 2023-06-04 13:33 UTC
Labels: bug, unconfirmed
