### ISSUE TITLE
Doesn't work on sodium 0.5.3

### ISSUE THREAD

**Issue by anoi1** [comp500/Indium#235] opened 2023-09-20 03:11 UTC
Doesn't work on sodium 0.5.3 +

**Comment by SorkoPiko** [comment] 2023-09-20 07:56
Same issue. Hope you will fix soon!

**Comment by mindryder** [comment] 2023-09-20 19:33
![Qx320LGCdM](https://github.com/comp500/Indium/assets/66848160/8b7f94ab-4508-4001-95b9-cd816d48dfa1)

**Comment by NoltoxGit** [comment] 2023-09-20 20:07
Hello @anoi1, @SorkoPiko & @mindryder !

You can download the latest version of Indium compatible with Fabric API `0.89.0` [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar) !

**Comment by BrycensRanch** [comment] 2023-09-20 20:38
thanks bro u a real one

**Comment by SorkoPiko** [comment] 2023-09-21 02:35
thanks!
also mods please close :)

**Comment by NoltoxGit** [comment] 2023-09-21 17:09
> thanks! also mods please close :)

It will be closed when the pull requests are accepted by the developer :)

**Comment by SorkoPiko** [comment] 2023-09-22 02:23
Didn't realise it hasn't been merged yet, sorry!

**Comment by comp500** [comment] 2023-09-23 00:11
Duplicate of #228

**Closed as not planned by comp500** 2023-09-23 00:11 UTC
