### ISSUE TITLE
Please support sodium 0.5.3

### ISSUE THREAD

**Issue by Luckylhz** [comp500/Indium#229] opened 2023-09-18 08:26 UTC
**Please support sodium 0.5.3**

**Comment by itsarian** [comment] 2023-09-18 11:27
duplicate issue
#228

**Comment by NoltoxGit** [comment] 2023-09-18 16:22
Hello @Luckylhz,
You can download this [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26%2Bmc1.20.1/indium-1.0.26+mc1.20.1.jar) !

**Comment by Notoriousi** [comment] 2023-09-19 14:30
Unsure if it works as intended. Still crashing when combined with continuity: https://mclo.gs/PhBPRnw

**Comment by Poopooracoocoo** [comment] 2023-09-19 14:38
@Notoriousi Indium needs to update to support Fabric API 0.89. You can downgrade to 0.88.1 for now.

**Comment by MeeniMc** [comment] 2023-09-20 02:20
Indeed, the prior release of Indium is already compatible with Sodium 0.5.3 (beside the version lock), but it is not compatible with the new Fabric API 0.89.

**Comment by mindryder** [comment] 2023-09-20 19:31
**Sodium release 4 days ago** 
![Qx320LGCdM](https://github.com/comp500/Indium/assets/66848160/2c69a419-e52d-42c5-b8e1-21ed7968bf21)

**Comment by comp500** [comment] 2023-09-23 00:08
Duplicate of #228

**Closed as not planned by comp500** 2023-09-23 00:08 UTC
