### ISSUE TITLE
Game crashes upon joining a world with a resource pack using emissive textures 

### ISSUE THREAD

**Issue by Jiggomase** [comp500/Indium#330] opened 2024-08-12 16:48 UTC
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

upon joining a world with a resource pack with emissive textures, the game crashes immediately with the error 'Chunk build failed, Tessellating block in world - Indium Renderer'.  

### Steps to Reproduce

1. Open Minecraft
2. Load a resource pack that features emissive textures (animated ores/visible ores)
3. Load a world

### Mod Version

1.0.34

### Minecraft Version

1.21

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/16589658/latest.log)

### Attach Crash Report

[crash-2024-08-12_18.26.08-client.txt](https://github.com/user-attachments/files/16589667/crash-2024-08-12_18.26.08-client.txt)

### Additional Information

I have installed all dependencies
Continuity is Installed.

**Comment by dmstewart42** [comment] 2024-08-12 19:51
#324

**Comment by comp500** [comment] 2024-08-15 16:50
Duplicate of #324

**Closed as not planned by comp500** 2024-08-15 16:50 UTC
Labels: bug
