### ISSUE TITLE
water and glass bug

### ISSUE THREAD

**Issue by ghost** [comp500/Indium#217] opened 2023-08-01 19:10 UTC
Hello everyone. I found a bug in the invidium mod, but I didn't find where to write. so I'll leave it here.

at the border of the chunk (that is, every 2 blocks), the water shines through if there is a multi-colored glass on it (not ordinary). and only from two sides.

**Comment by comp500** [comment] 2023-08-01 20:08
By "invidium" do you mean [Nvidium](https://github.com/MCRcortex/nvidium/issues)? It's likely to be https://github.com/CaffeineMC/sodium-fabric/issues/38 - translucency sorting / Order Independent Transparency is not yet implemented in Sodium, as this is a difficult problem to solve.

**Comment by comp500** [comment] 2023-08-14 21:57
Closing: this is unlikely to be caused by Indium.

**Closed as not planned by comp500** 2023-08-14 21:57 UTC
