### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by CreepyHobo** [comp500/Indium#211] opened 2023-07-14 06:41 UTC
Tonight I was playing my 1.20.1 world and out of know where the game crashed with this message: The game crashed whilst unexpected error Error: java.util.concurrent.CompletionException: net.minecraft.class_148: Tessellating block in world - Indium Renderer

I saw another person had something similar issue happen in 1.19 who was much more tech savvy than I.

After looking closer at the older post about this similar bug, I looked for an update for Fabric API and found a newer version (0.85.0), so I installed that.  If there's anything else I can do to help you diagnose this let me know I'll do my best with the limited end user abilities that I have.  😄

Thanks for your hard work developing this mod!  I'm sure it's helping the performance of Minecraft in ways I'll never understand but appreciate none the less.  Attached is a copy of the crash log.

[crash-2023-07-14_01.17.39-client.txt](https://github.com/comp500/Indium/files/12046902/crash-2023-07-14_01.17.39-client.txt)

**Comment by comp500** [comment] 2023-07-14 08:59
Duplicate of #199

**Closed as not planned** 2023-07-14 08:59 UTC
