### ISSUE TITLE
[BUG] Z-fighting w. Snow! Real Magic!

### ISSUE THREAD

**Issue by Shazuli** [comp500/Indium#139] opened 2022-09-26 13:44 UTC
***Hi***

[Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-fabric) improves snow by allowing most non-full blocks to render snow on it:
![2022-09-26_15 34 05](https://user-images.githubusercontent.com/9884180/192292231-6b54a10a-5b08-4dd3-ac70-5095d43c0960.png)

However, with Sodium installed this rendering will not work and makes the block invisible. But after installing Indium the block render is back but on two of the sides of most blocks there occurs Z-fighting.

#### Good side
![2022-09-26_15 34 46](https://user-images.githubusercontent.com/9884180/192291436-22d3732d-34e6-47b0-acc6-037ba02d0fab.png)

#### Z-fighting (hard to show from a static image)
![2022-09-26_15 34 56](https://user-images.githubusercontent.com/9884180/192291582-9a004409-2918-4ca1-b84c-f905ef9b2c89.png)

#### Good side
![2022-09-26_15 32 49](https://user-images.githubusercontent.com/9884180/192291799-9aa44ed3-e278-44de-9f46-b3a2511c85c1.png)

#### Z-fighting
![2022-09-26_15 33 00](https://user-images.githubusercontent.com/9884180/192291879-853691c3-2f8d-4688-bda9-dff65acd163d.png)

**Comment by comp500** [comment] 2022-09-26 21:11
Does this still occur if you disable the Compact Vertex Format in Sodium's advanced options? The author might need to increase the vertex offset of the added faces for it to be compatible with this Sodium optimisation.

**Comment by Shazuli** [comment] 2022-09-27 08:13
Umm, not sure what option you mean with "Compact Vertex Format".
![image](https://user-images.githubusercontent.com/9884180/192470615-0f69fa76-d96a-4c4e-be61-905c0876b9f8.png)

![image](https://user-images.githubusercontent.com/9884180/192470888-3cc3f352-061d-4df9-876c-5925f6cbbcb9.png)

**Comment by comp500** [comment] 2022-09-27 12:13
Ah I forgot, it isn't a configurable option in current release versions of Sodium (it was in 0.2, and upcoming 0.5). I don't think this is something that is caused by or can be fixed by Indium - it's an implication of Sodium's compact vertex format, which will require slight changes to the code of Snow! Real Magic! to increase the offset of the added faces (as Sodium uses lower precision for position data) or disabling of the compact vertex format (which should be possible in the 0.5 Sodium release).

**Closed as completed by comp500** 2022-09-27 12:13 UTC
