### ISSUE TITLE
Fabric API 0.89.0 update crashes minecraft when Indium is also there and being used

### ISSUE THREAD

**Issue by TheGinGear** [comp500/Indium#236] opened 2023-09-20 03:32 UTC
Fabulously Optimized 5.3.1 with only Fabric API updated:
<details>
 <summary>Mod list</summary>
 
![image](https://github.com/comp500/Indium/assets/39550332/337342b2-e66b-4145-91f2-815f3e2ec11f)

</details>
Logs: 

https://mclo.gs/1Ljz4Am
[1Ljz4Am.txt](https://github.com/comp500/Indium/files/12668280/1Ljz4Am.txt)

Crash report:
[crash-2023-09-19_22.27.28-client.txt](https://github.com/comp500/Indium/files/12668287/crash-2023-09-19_22.27.28-client.txt)

Disabling Indium allows the modpack to launch just fine with the updated fabric API.

Logs:
https://mclo.gs/q6OXWUm
[q6OXWUm.txt](https://github.com/comp500/Indium/files/12668292/q6OXWUm.txt)

**Comment by NoltoxGit** [comment] 2023-09-20 20:06
> Fabulously Optimized 5.3.1 with only Fabric API updated:
> 
> Mod list
> Logs:
> https://mclo.gs/1Ljz4Am [1Ljz4Am.txt](https://github.com/comp500/Indium/files/12668280/1Ljz4Am.txt)
> 
> Crash report: [crash-2023-09-19_22.27.28-client.txt](https://github.com/comp500/Indium/files/12668287/crash-2023-09-19_22.27.28-client.txt)
> 
> Disabling Indium allows the modpack to launch just fine with the updated fabric API.
> 
> Logs: https://mclo.gs/q6OXWUm [q6OXWUm.txt](https://github.com/comp500/Indium/files/12668292/q6OXWUm.txt)

Hello,

You can download the latest version of Indium compatible with Fabric API `0.89.0` [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar) !

**Comment by comp500** [comment] 2023-09-23 00:18
Duplicate of #232

**Closed as not planned by comp500** 2023-09-23 00:18 UTC
