### ISSUE TITLE
Exceptions after loading

### ISSUE THREAD

**Issue by imcasper** [comp500/Indium#104] opened 2022-02-10 16:14 UTC
After loading the game, getting several errors at once 

java: 17
minecraftVersion: 1.16.5
yarnMappings: 1.16.5+build.10
loaderVersion: 0.13.0
fabricVersion: 0.42.0+1.16

java.lang.NullPointerException: Cannot read field "lastNauseaStrength" because "this.client.player" is null
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:705)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:546)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1048)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Also:**
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "this.descriptor" is null
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [indium.mixins.json:sodium.MixinChunkRenderRebuildTask] from phase [DEFAULT] in config [indium.mixins.json] from mod [indium] FAILED during APPLY
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Error whilst instancing injection point org.spongepowered.asm.mixin.injection.points.BeforeInvoke for INVOKE [PREINJECT Applicator Phase -> indium.mixins.json:sodium.MixinChunkRenderRebuildTask -> Prepare Injections ->  -> redirect$zkf000$onRenderBlock(Lme/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer;Lnet/minecraft/world/BlockRenderView;Lnet/minecraft/block/BlockState;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/client/render/model/BakedModel;Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuffers;ZJ)Z -> Parse]
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "this.descriptor" is null
Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 255

[crash-2022-02-10_19.10.47-client.txt](https://github.com/comp500/Indium/files/8042522/crash-2022-02-10_19.10.47-client.txt)

**Comment by comp500** [comment] 2022-02-10 16:31
That... shouldn't happen? Please try redownloading Sodium and Indium from Modrinth/CurseForge, and testing without any other mods (apart from Fabric API).

**Comment by imcasper** [comment] 2022-02-10 16:47
.../mods/fabric-api-0.42.0+1.16.jar
../mods/indium-1.0.0+mc1.16.5.jar
../sodium-fabric-mc1.16.5-0.2.0+build.4.jar
I try this config... And all work...
Now I'm looking for the configuration causing the error

**Comment by imcasper** [comment] 2022-03-04 07:11
I have equal exception for
minecraft 1.18.1...

I restart game only with this mod:

fabric-api-0.46.4+1.18.jar
indium-1.0.2-alpha3+mc1.18.1.jar
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

And catch exception too.

**Comment by comp500** [comment] 2022-03-04 17:56
Could you send the full `logs/latest.log` file? This set of mods works perfectly fine for me.

**Comment by Draylar** [comment] 2022-03-17 22:48
Just wanted to chime in and say I'm encountering the same issue inside a development environment (Sodium & Indium jar inside `/run/mods/`) running the same versions:
```
Fabric API - 0.46.4+1.18
Sodium - sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14
Indium - indium-1.0.2-alpha3+mc1.18.1
Fabric Loader - 0.13.3
Minecraft - 1.18.1
```
I'm not able to send a full log, [but the error is the same](https://pastebin.com/iPZjZSGC). I recall reading an issue somewhere about Indium (or Sodium) jars having issues when remapped inside a development environment, so that might be related to this problem.

**Comment by comp500** [comment] 2022-03-17 23:27
See https://github.com/FabricMC/Mixin/issues/55 for the issue in a dev environment; I think the crash in this issue is something different as it isn't in a dev env - your crash is caused by trying to remap Indium mixins to the dev env names.

**Comment by imcasper** [comment] 2022-03-18 08:41
Unfortunately I can't find the log right now. The problem is most likely due to version incompatibilities. I tried different official releases of the required mods - the problem remained.

I solved it by rebuilding my version of mods (both sodium and indium), (changed only api/fabric/library versions in gradle)

**Comment by comp500** [comment] 2023-06-04 13:27
Closing: unable to replicate crash and rather old (if this happens again in a newer version, please report it!)

**Closed as not planned by comp500** 2023-06-04 13:27 UTC
Labels: bug, unconfirmed
