### ISSUE TITLE
Crashes when useing texture pack

### ISSUE THREAD

**Issue by 888Ghost888** [comp500/Indium#328] opened 2024-08-10 19:39 UTC
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

the game crashes when loading world and it says it is a tessellating block issue... 

if installed and texture pack is off when loading the world it will say that it is a resource load fail when turning the pack on...

### Steps to Reproduce

1. install indium(MOD), continuality(MOD), and better Ores 3d(resorce pack)
2. launch MC.
3. open a world

### Mod Version

indium 1.0.34

### Minecraft Version

Minecraft 1.21

### Attach latest.log

n/a

Can find

### Attach Crash Report

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-08-10 12:35:54
Description: Tessellating block in world - Indium Renderer

java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:64)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:72)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$cfa000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:64)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:72)

-- Block being tessellated --
Details:
	Block: Block{minecraft:stone}
	Block location: World: (-816,64,352), Section: (at 0,0,0 in -51,4,22; chunk contains blocks -816,-64,352 to -801,319,367), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
Stacktrace:
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$cfa000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Block being rendered --
Details:
	Block: Block{minecraft:stone}
	Block location: World: (-816,64,352), Section: (at 0,0,0 in -51,4,22; chunk contains blocks -816,-64,352 to -801,319,367), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,-64,0 to -513,319,511)
	Chunk section: RenderSection at chunk (-51, 4, 22) from (-816, 64, 352) to (-801, 79, 367)
	Render context volume: class_3341{minX=-818, minY=62, minZ=350, maxX=-799, maxY=81, maxZ=369}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Uptime --
Details:
	JVM uptime: 161.625s
	Wall uptime: 149.972s
	High-res time: 145.297s
	Client ticks: 2580 ticks / 129.000s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['ImPacman15'/489, l='ClientLevel', x=-806.77, y=70.00, z=354.34]]
	Chunk stats: 4096, 878
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,67,16), Section: (at 0,3,0 in -15,4,1; chunk contains blocks -240,-64,16 to -225,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 84379 game time, 144745 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 184

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, advancementplaques, appleskin, balm-fabric, betteradvancements, betterf3, betterstats, biomeinfo, blur, bobby, cardinal-components-base, cardinal-components-block, cardinal-components-entity, chat_heads, chatanimation, chunksfadein, cicada, clickadv, cloth-config, colorfulhearts, colorfulsubtitles, continuity, craftingtweaks, creativecore, damagenumbers, do_a_barrel_roll, durabilitytooltip, eatinganimationid, enhancedvisuals, entity_model_features, entity_texture_features, equipmentcompare, expcounter, explayerenderer, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fallingleaves, firstperson, forgeconfigapiport, ftblibrary, ftbultimine, guifollowers, indium, inventoryhud, inventoryprofilesnext, itemphysic, jade, jamlib, jankson, jei, journeymap, justenoughbreeding, justenoughprofessions, legendarytooltips, libgui, libipn, lithium, make_bubbles_pop, merchantmarkers, midnightlib, mobhealthbar, modmenu, motionblur, my-totem-doll, namepain, nicer-skies, notes, owo, placeholder-api, pling, polymorph, polytone, presencefootsteps, prism, reputation, rightclickharvest, satin, searchables, shouldersurfing, showmeyourskin, smoothgui, sodium, sound_physics_remastered, tcdcommons, trajectory-preview, visuality, watut, weaponmaster_ydm, yet_another_config_lib_v3, yigd, zoomify, file/Better-Leaves-8.0-1.20+.zip, file/Beautiful_Enchanted_Books_3.0.0_MC-1.21.zip, file/EnderEyes_1.21_v3.1.zip, file/Eyeless Fresh Moves v3.0.1.zip, file/FA+All_Extensions-v1.4.zip, file/FreshAnimations_v1.9.2.zip, file/MandalasGUI+Dakmode_1.20.5.zip, file/Nebula Glint Blue.zip, minecraft:supporteatinganimation, presencefootsteps:default_sound_pack, file/Mahi's Better Sky V1.2.0 (1.21).zip, file/Fast Better Grass.zip, file/§bBetter§3Ores§f-§91.21§0.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1045299080 bytes (996 MiB) / 2275409920 bytes (2170 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 128.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.5186
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 19746.13
	Virtual memory used (MiB): 16310.49
	Swap memory total (MiB): 3584.00
	Swap memory used (MiB): 47.35
	Space in storage for jna.tmpdir (MiB): available: 81131.05, total: 487269.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 81131.05, total: 487269.00
	Space in storage for io.netty.native.workdir (MiB): available: 81131.05, total: 487269.00
	Space in storage for java.io.tmpdir (MiB): available: 81131.05, total: 487269.00
	Space in storage for workdir (MiB): available: 81131.05, total: 487269.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.6.6
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		balm-fabric: Balm 21.0.14
			kuma_api: KumaAPI 21.0.4
		betteradvancements: Better Advancements 0.4.2.16
		betterf3: BetterF3 11.0.1
		betterstats: Better Statistics Screen 3.12.6+fabric-1.21
		biomeinfo: BiomeInfo 1.21-18
		blur: Blur+ (Fabric) 4.1.0
			midnightlib: MidnightLib 1.5.7
		bobby: Bobby 5.2.3+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		chat_heads: Chat Heads 0.12.10
		chatanimation: ChatAnimation 1.0.6
		chunksfadein: Chunks Fade In 1.0.1-1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			crowdin-translate: CrowdinTranslate 1.0.0
		cicada: CICADA 0.8.3+1.21-and-above
		clickadv: Clickable Advancements Mod 1.21-3.8
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.81
		colorfulhearts: Colorful Hearts 10.0.0
		colorfulsubtitles: Colorful Subtitles 1.5.0
		continuity: Continuity 3.0.0-beta.5+1.21
		coroutil: CoroUtil 1.21.0-1.3.7
		craftingtweaks: Crafting Tweaks 21.0.3
		creativecore: CreativeCore 2.12.6
			net_neoforged_bus: bus 7.2.0
		cupboard: cupboard 1.21-2.7
		damagenumbers: Damage Numbers 1.4.1-fabric
		do_a_barrel_roll: Do a Barrel Roll 3.6.1+1.21
			mixinsquared: MixinSquared 0.1.1
		doubledoors: Double Doors 5.9
		durabilitytooltip: Durability Tooltip 1.1.5
		eatinganimationid: Eating Animation 1.21+1.9.72
		enhancedvisuals: EnhancedVisuals 1.8.6
		entity_model_features: Entity Model Features 2.1.3
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		equipmentcompare: Equipment Compare 1.3.12
		expcounter: EXPCounter 1.21-1-fabric
		explayerenderer: ExtraPlayerRenderer 3.0.0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.0+kotlin.2.0.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		fallingleaves: Falling Leaves 1.16.2
		firstperson: FirstPerson 2.4.4
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		ftblibrary: FTB Library 2100.1.4
		ftbultimine: FTB Ultimine 2100.1.0
		glitchcore: GlitchCore 2.0.0.2
			net_jodah_typetools: typetools 0.6.3
		guifollowers: GUI Followers 3.8
		iceberg: Iceberg 1.2.4
		indium: Indium 1.0.34+mc1.21
		inventoryhud: Inventory HUD + 3.4.24
		inventoryprofilesnext: Inventory Profiles Next 2.0.4
		itemphysic: ItemPhysic 1.7.2
		jade: Jade 15.1.5+fabric
		jamlib: JamLib 1.0.11+1.21
			blue_endless_jankson: jankson 1.2.3
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.8.2.99
		journeymap: Journeymap 1.21-6.0.0-beta.19
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.11-1.21
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21-SNAPSHOT
		justenoughbreeding: Just Enough Breeding 1.2.4
		justenoughprofessions: Just Enough Professions (JEP) 4.0.1
		legendarytooltips: Legendary Tooltips 1.4.11
		libipn: libIPN 6.0.2
		lithium: Lithium 0.12.7
		make_bubbles_pop: Make Bubbles Pop 0.3.0-fabric
		merchantmarkers: Merchant Markers 1.3.5
		minecraft: Minecraft 1.21
		mobhealthbar: MobHealthBar 2.3.0
		modmenu: Mod Menu 11.0.1
		motionblur: Motion Blur 1.0.5+mc1.21
		mousetweaks: Mouse Tweaks 2.26
		my-totem-doll: My Totem Doll 1.0.1+1.21
		namepain: Name Pain 1.5.3
		nicer-skies: Nicer Skies 1.4.0+1.21
		notes: Notes 1.21-2.1.1-fabric
		nyfsspiders: Nyf's Spiders 2.3.0
		owo: oωo 0.12.11+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		pickupnotifier: Pick Up Notifier 21.0.0
		placeholder-api: Placeholder API 2.4.1+1.21
		pling: Pling 1.8.1
		polymorph: Polymorph 1.0.4+1.21
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-block: Cardinal Components API (blocks) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		polytone: Polytone 1.21-2.3.3
			net_objecthunter_exp4j: exp4j 0.4.8
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		prism: root project 'Prism' 1.0.8
		puzzleslib: Puzzles Lib 21.0.20
		reputation: Your Reputation 0.2.7+jade.1.21
		rightclickharvest: Right Click Harvest 4.3.1+1.21
		satin: Satin 2.0.0
		searchables: Searchables 1.0.5
		shouldersurfing: Shoulder Surfing Reloaded 4.3.0
		showmeyourskin: Show Me Your Skin! 1.11.2+1.21
		smoothgui: SmoothGui 0.1.1
		smoothscrollingrefurbished: Smooth Scrolling Refurbished 1.1.4
		sodium: Sodium 0.5.11+mc1.21
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		tcdcommons: TCD Commons API 3.12.3+fabric-1.21
		trajectory-preview: Trajectory Preview 4.0-1.21
		villagernames: Villager Names 8.1
		visuality: Visuality 0.7.7+1.21
		watut: What Are They Up To 1.21.0-1.1.3
		weaponmaster_ydm: YDM's Weapon Master 4.2.3
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yigd: You're in Grave Danger 2.4.2
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			libgui: LibGui 11.0.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
		zoomify: Zoomify 2.14.0+1.21
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Launched Version: fabric-loader-0.16.0-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 31.0.101.5186, Intel
	Window size: 1528x944
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 15/15 chunks
	Resource Packs: vanilla, fabric, advancementplaques, appleskin (incompatible), balm-fabric (incompatible), betteradvancements (incompatible), betterf3, betterstats, biomeinfo, blur, bobby, cardinal-components-base, cardinal-components-block, cardinal-components-entity, chat_heads, chatanimation, chunksfadein, cicada, clickadv (incompatible), cloth-config, colorfulhearts, colorfulsubtitles, continuity, craftingtweaks (incompatible), creativecore, damagenumbers, do_a_barrel_roll (incompatible), durabilitytooltip, eatinganimationid, enhancedvisuals, entity_model_features, entity_texture_features, equipmentcompare, expcounter, explayerenderer, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fallingleaves, firstperson, forgeconfigapiport, ftblibrary, ftbultimine, guifollowers (incompatible), indium, inventoryhud, inventoryprofilesnext, itemphysic, jade (incompatible), jamlib, jankson, jei (incompatible), journeymap, justenoughbreeding (incompatible), justenoughprofessions (incompatible), legendarytooltips, libgui, libipn, lithium, make_bubbles_pop, merchantmarkers, midnightlib, mobhealthbar, modmenu, motionblur, my-totem-doll, namepain, nicer-skies, notes, owo, placeholder-api, pling, polymorph (incompatible), polytone, presencefootsteps, prism, reputation, rightclickharvest, satin, searchables (incompatible), shouldersurfing, showmeyourskin, smoothgui, sodium, sound_physics_remastered, tcdcommons, trajectory-preview, visuality, watut (incompatible), weaponmaster_ydm, yet_another_config_lib_v3 (incompatible), yigd, zoomify, file/Better-Leaves-8.0-1.20+.zip, file/Beautiful_Enchanted_Books_3.0.0_MC-1.21.zip, file/EnderEyes_1.21_v3.1.zip, file/Eyeless Fresh Moves v3.0.1.zip, file/FA+All_Extensions-v1.4.zip, file/FreshAnimations_v1.9.2.zip, file/MandalasGUI+Dakmode_1.20.5.zip (incompatible), file/Nebula Glint Blue.zip (incompatible), minecraft:supporteatinganimation, presencefootsteps:default_sound_pack, file/Mahi's Better Sky V1.2.0 (1.21).zip, file/Fast Better Grass.zip, file/§bBetter§3Ores§f-§91.21§0.zip
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['ImPacman15'/489, l='ServerLevel[Grandma]', x=-806.77, y=70.00, z=354.34]]
	Active Data Packs: vanilla, fabric, balm-fabric (incompatible), collective, craftingtweaks (incompatible), fabric-convention-tags-v2, ftbultimine, rightclickharvest, yigd
	Available Data Packs: balm-fabric (incompatible), bundle, collective, craftingtweaks (incompatible), fabric, fabric-convention-tags-v2, ftbultimine, rightclickharvest, trade_rebalance, vanilla, yigd
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 1944933248

**Comment by dmstewart42** [comment] 2024-08-11 01:45
I believe this is a duplicate of #324, #325, #326, and #327

**Comment by ironvaliante** [comment] 2024-08-12 10:04
Its caused by indium but without indium continuity wont work

**Comment by comp500** [comment] 2024-08-15 16:49
Duplicate of #324

**Closed as not planned by comp500** 2024-08-15 16:49 UTC
Labels: bug
