### ISSUE TITLE
Crashing when loading a world...

### ISSUE THREAD

**Issue by X0L4N** [comp500/Indium#326] opened 2024-08-07 05:18 UTC
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

Crashes while trying to load up a world. Minecraft  boots up fine, menu and settings work, but crashes right as the world is loading in. I have tried excluding any unnecessary mods and tried excluding Indium, when I remove Indium, I can load worlds, play the game but due to continuity requiring indium it crashes in case of a block that is affected by gravity (sand, gravel etc.) falls or gets moved at all. So I tried everything in my power to find the reason but I have been unable to. For context, this is for my own playthrough, not for any modpack or social network at all.
 

### Steps to Reproduce

1. Open Minecraft
2. Load world, any world (includes new creation)

### Mod Version

1.0.34

### Minecraft Version

1.21

### Attach latest.log

[08:10:50] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.16.0
[08:10:51] [main/INFO]: Loading 96 mods:
	- animatica 0.6.1+1.21
	- architectury 13.0.6
	- continuity 3.0.0-beta.5+1.21
	- entity_model_features 2.1.3
	- entity_texture_features 6.1.3
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- fabric-api 0.101.1+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.68+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.16+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.19+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.5.0+c5e2b5c6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.26+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.15+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.11+ba9dae06d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.4+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df360d1
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.1+8759e755d1
	   |-- fabric-object-builder-api-v1 15.1.14+d1321076d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.11+65089712d1
	   |-- fabric-registry-sync-v0 5.1.1+0a3a0057d1
	   |-- fabric-renderer-api-v1 3.4.0+c705a49cd1
	   |-- fabric-renderer-indigo 1.7.0+c705a49cd1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b1d1
	   |-- fabric-resource-loader-v0 1.3.0+56599129d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.85+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.16+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.1.0+176f9036d1
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.16.0
	   \-- mixinextras 0.4.0
	- forgeconfigapiport 21.0.7
	   |-- com_electronwill_night-config_core 3.8.0
	   \-- com_electronwill_night-config_toml 3.8.0
	- ftblibrary 2100.1.4
	- ftbultimine 2100.1.0
	- iceberg 1.2.4
	- ichunutil 1.0.0
	- indium 1.0.34+mc1.21
	- iris 1.7.3+mc1.21
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- jade 15.1.5+fabric
	- java 21
	- minecraft 1.21
	- modmenu 11.0.1
	   \-- placeholder-api 2.4.0-pre.2+1.21
	- optigui 2.3.0-beta.2+1.21
	   |-- org_apache_commons_commons-text 1.12.0
	   \-- org_ini4j_ini4j 0.5.4
	- prism 1.0.8
	- puzzleslib 21.0.18
	- reeses-sodium-options 1.7.3+mc1.21
	- sodium 0.5.11+mc1.21
	- sodium-extra 0.5.7+mc1.21
	   \-- caffeineconfig 1.3.0+1.17
	- supermartijn642configlib 1.1.8
[08:10:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/yeygs/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.0+mixin.0.8.7/sponge-mixin-0.15.0+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[08:10:52] [main/INFO]: Compatibility level set to JAVA_16
[08:10:52] [main/INFO]: Compatibility level set to JAVA_21
[08:10:52] [main/WARN]: Reference map 'forgeconfigapiport.common.refmap.json' for forgeconfigapiport.common.mixins.json could not be read. If this is a development environment you can ignore this message
[08:10:53] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[08:10:53] [main/INFO]: Loaded configuration file for Sodium Extra: 35 options available, 0 override(s) found
[08:10:53] [main/WARN]: Reference map 'supermartijn642configlib.mixins.refmap.json' for supermartijn642configlib.mixins.json could not be read. If this is a development environment you can ignore this message
[08:10:53] [main/WARN]: Error loading class: net/raphimc/immediatelyfast/feature/core/ImmediateAdapter (java.lang.ClassNotFoundException: net/raphimc/immediatelyfast/feature/core/ImmediateAdapter)
[08:10:54] [main/WARN]: Error loading class: dev/tr7zw/skinlayers/render/CustomizableModelPart (java.lang.ClassNotFoundException: dev/tr7zw/skinlayers/render/CustomizableModelPart)
[08:10:54] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/vertex/buffer/SodiumBufferBuilder (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/vertex/buffer/SodiumBufferBuilder)
[08:10:54] [main/WARN]: Error loading class: net/raphimc/immediatelyfast/feature/core/BatchableBufferSource (java.lang.ClassNotFoundException: net/raphimc/immediatelyfast/feature/core/BatchableBufferSource)
[08:10:55] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[08:10:55] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[08:10:55] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[08:10:55] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[08:10:55] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[08:10:55] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[08:10:55] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[08:10:55] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[08:10:56] [main/INFO]: Searching for graphics cards...
[08:10:57] [main/INFO]: Found graphics adapter: AdapterInfo{vendor=INTEL, description='Intel(R) HD Graphics 620', adapterType=0x0000032B, openglIcdFilePath='C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_c34fd594e40bf436\ig9icd64.dll', openglIcdVersion=27.20.100.9664}
[08:10:57] [main/INFO]: Found graphics adapter: AdapterInfo{vendor=AMD, description='AMD Radeon R7 M440', adapterType=0x00000011, openglIcdFilePath='atig6pxx.dll', openglIcdVersion=8.14.1.6521}
[08:10:58] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.0).
[08:11:05] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 3433 milliseconds
[08:11:20] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[08:11:20] [Render thread/INFO]: Setting user: X0L4N
[08:11:21] [Render thread/INFO]: Registering S2C receiver with id ftblibrary:edit_config
[08:11:21] [Render thread/INFO]: Registering S2C receiver with id ftblibrary:edit_nbt
[08:11:21] [Render thread/INFO]: Registering S2C receiver with id ftblibrary:sync_known_server_registries
[08:11:21] [Render thread/INFO]: Registering C2S receiver with id ftblibrary:edit_nbt_response
[08:11:21] [Render thread/INFO]: Registering S2C receiver with id ftbultimine:send_shape_packet
[08:11:21] [Render thread/INFO]: Registering S2C receiver with id ftbultimine:sync_config_from_server_packet
[08:11:21] [Render thread/INFO]: Registering S2C receiver with id ftbultimine:edit_config_packet
[08:11:21] [Render thread/INFO]: Registering S2C receiver with id ftbultimine:sync_ultimine_time_packet
[08:11:21] [Render thread/INFO]: Registering C2S receiver with id ftbultimine:key_pressed_packet
[08:11:21] [Render thread/INFO]: Registering C2S receiver with id ftbultimine:mode_changed_packet
[08:11:21] [Render thread/INFO]: Registering C2S receiver with id ftbultimine:sync_config_to_server_packet
[08:11:21] [Render thread/INFO]: Constructing common components for puzzleslib:main
[08:11:21] [Render thread/INFO]: Registering S2C receiver with id architectury:spawn_entity_packet
[08:11:22] [Render thread/INFO]: Loading Entity Model Features, we get there when we get there.
[08:11:22] [Render thread/INFO]: 6 new ETF Random Properties registered by entity_model_features.
[08:11:22] [Render thread/INFO]: Loading Entity Texture Features, the worst server plugin one guy on my discord has ever seen!
[08:11:22] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[08:11:23] [Render thread/INFO]: Checking mod updates...
[08:11:26] [Render thread/INFO]: Constructing client components for puzzleslib:main
[08:11:27] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[08:11:27] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] This version doesn't have an update index, skipping.
[08:11:29] [Render thread/INFO]: Debug functionality is disabled.
[08:11:29] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[08:11:29] [Render thread/INFO]: Shaders are disabled because enableShaders is set to false in iris.properties
[08:11:29] [Render thread/INFO]: Found non-pack entry 'C:\Users\yeygs\AppData\Roaming\.minecraft\resourcepacks\DS4Windows_3.3.3_x64', ignoring
[08:11:30] [Render thread/INFO]: Hardware information:
[08:11:30] [Render thread/INFO]: CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
[08:11:30] [Render thread/INFO]: GPU: Intel(R) HD Graphics 620 (Supports OpenGL 3.2.0 - Build 27.20.100.9664)
[08:11:30] [Render thread/INFO]: OS: Windows 10 (10.0)
[08:11:31] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, animatica, caffeineconfig, continuity, entity_model_features, entity_texture_features, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, ftblibrary, ftbultimine, ichunutil, indium, iris, jade, modmenu, optigui, prism, reeses-sodium-options, sodium, sodium-extra, continuity:glass_pane_culling_fix, continuity:default, file/FreshAnimations_v1.9.2
[08:11:31] [Render thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.core.CorePlugin
[08:11:31] [Worker-Main-2/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[08:11:31] [Render thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.vanilla.VanillaPlugin
[08:11:32] [Render thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.universal.UniversalPlugin
[08:11:32] [Render thread/INFO]: Start loading plugin from Jade: snownee.jade.addon.debug.DebugPlugin
[08:11:32] [Worker-Main-2/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[08:11:36] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[08:11:36] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[08:11:36] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (KYRUSE)
[08:11:36] [Render thread/INFO]: Sound engine started
[08:11:36] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[08:11:36] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[08:11:36] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[08:11:36] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[08:11:36] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[08:11:36] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[08:11:36] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[08:11:36] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[08:11:36] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[08:11:38] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[08:11:40] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[08:11:40] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[08:11:40] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[08:11:40] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[08:11:40] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[08:11:41] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[08:11:41] [Render thread/INFO]: reloading ETF data.
[08:11:41] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[08:11:41] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[08:11:56] [Render thread/INFO]: Loaded 1290 recipes
[08:11:57] [Render thread/INFO]: Loaded 1399 advancements
[08:11:57] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 2.911 ms
[08:11:58] [Server thread/INFO]: Starting integrated minecraft server version 1.21
[08:11:58] [Server thread/INFO]: Generating keypair
[08:12:03] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[08:12:05] [Render thread/INFO]: Preparing spawn area: 0%
[08:12:05] [Render thread/INFO]: Preparing spawn area: 0%
[08:12:05] [Render thread/INFO]: Preparing spawn area: 0%
[08:12:05] [Render thread/INFO]: Time elapsed: 1419 ms
[08:12:05] [Server thread/INFO]: Changing view distance to 12, from 10
[08:12:05] [Server thread/INFO]: Changing simulation distance to 12, from 0
[08:12:07] [Server thread/INFO]: X0L4N[local:E:4cdf4f4f] logged in with entity id 3 at (-23.427325931096995, 42.76268367033254, 220.4391788680245)
[08:12:08] [Server thread/INFO]: X0L4N joined the game
[08:12:08] [Render thread/INFO]: Reloading pipeline on dimension change: minecraft:overworld => minecraft:overworld
[08:12:08] [Render thread/INFO]: Destroying pipeline minecraft:overworld
[08:12:08] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[08:12:08] [Render thread/INFO]: Started 2 worker threads
[08:12:09] [Render thread/INFO]: Received config from the server: 
[08:12:09] [Render thread/INFO]: Loaded 119 advancements
[08:12:09] [Render thread/INFO]: received server config settings
[08:12:11] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.cod.ambient
[08:12:12] [Chunk Render Task Executor #0/ERROR]: Chunk build failed
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-2beb50691e4ea51.jar:?]
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.34+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bgm000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	... 4 more
[08:12:12] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.4.0+c705a49cd1-2beb50691e4ea51.jar:?]
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53) ~[continuity-3.0.0-beta.5+1.21.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.34+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bgm000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-0.5.11+mc1.21.jar:?]
	... 4 more
[08:12:13] [Server thread/INFO]: Stopping server
[08:12:13] [Server thread/INFO]: Saving players
[08:12:13] [Server thread/INFO]: Saving worlds
[08:12:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[CreeperFarmWorld]'/minecraft:overworld
[08:12:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[CreeperFarmWorld]'/minecraft:the_end
[08:12:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[CreeperFarmWorld]'/minecraft:the_nether
[08:12:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (CreeperFarmWorld): All chunks are saved
[08:12:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[08:12:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[08:12:14] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[08:12:14] [Render thread/INFO]: Stopping worker threads
[08:12:14] [Render thread/INFO]: emissive suffixes loaded: {_e}.

### Attach Crash Report

The game crashed whilst tessellating block in world - indium renderer
Error: java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'

**Comment by Adama2k-1** [comment] 2024-08-07 08:58
I can confirm--having the same exact issue. It seems the latest versions of FabricAPI  >=0.101.0 have broken Indium's rendering. Unfortunately the only fix I could do at the moment is downgrade to FabricAPI 0.100.8 and hope it isn't too big an issue to be patched!

**Comment by TheBossMagnus** [comment] 2024-08-07 13:37
Duplicate of https://github.com/comp500/Indium/issues/324

**Comment by solonoturningpoint** [comment] 2024-08-08 07:27
UPDATE IT BRO, GLASS BLOCKS ARE SO FREAKIN UGLY WITHOUT YOUR MOD 😞

**Comment by solonoturningpoint** [comment] 2024-08-08 07:46
> I can confirm--having the same exact issue. It seems the latest versions of FabricAPI >=0.101.0 have broken Indium's rendering. Unfortunately the only fix I could do at the moment is downgrade to FabricAPI 0.100.8 and hope it isn't too big an issue to be patched!

this seems to have fixed it, thanks...

**Comment by SpokenWig620933** [comment] 2024-08-10 11:20
Duplicate of #324

**Comment by comp500** [comment] 2024-08-15 16:49
Duplicate of #324

**Closed as not planned by comp500** 2024-08-15 16:49 UTC
Labels: bug
