### ISSUE TITLE
Entities going invisible and game crashing after opening REI

### ISSUE THREAD

**Issue by chorbintime** [comp500/Indium#194] opened 2023-05-20 01:08 UTC
Hi, I'm a developer for [Medieval MC Fabric](https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric), we just received a report from a user that claims they were "just walking throughout a nether castle and boom all mobs turned invisible, including myself, (i later learned its not mobs, but entities. chests, armor stands, items, etc etc)".

It seems to be similar to #166 and #186?

It seems to be Indium related due to how many times the mod is blamed, but it could be the fault of Continuity or REI.

[latest (25).log](https://github.com/comp500/Indium/files/11521254/latest.25.log)
[message (10).txt](https://github.com/comp500/Indium/files/11521255/message.10.txt)

**Comment by chorbintime** [comment] 2023-05-20 01:48
Here is their world file: https://www.mediafire.com/file/mg3apr2ezv1z7fm/Chaos_-_Copy.zip/file

**Comment by comp500** [comment] 2023-05-20 03:32
As mentioned in #166, I don't believe this is an Indium issue rather that of ImmediatelyFast (and possibly owo lib?), but as far as I know neither I nor the developer of ImmediatelyFast has been able to reproduce the issue.

Indium only shows up in the stack trace because, like Indigo in Fabric API, it takes over item rendering to support FRAPI models (in this context being rendered for the REI GUI). Any crash related to item rendering will show it in the stacktrace regardless of whether it is involved in causing the crash.

**Comment by comp500** [comment] 2023-06-04 13:23
Duplicate of #166

**Closed as not planned by comp500** 2023-06-04 13:23 UTC
