### ISSUE TITLE
World crashes with a white screen

### ISSUE THREAD

**Issue by lukas27892** [comp500/Indium#234] opened 2023-09-19 18:26 UTC
https://mclo.gs/Nji4rCI
using 1.20.1
sodium 0.5.2
iris
and indium (obviously)

**Comment by iofloodMichael** [comment] 2023-09-19 21:46
looks like the exact same issue (and versions) for me as well :(

**Comment by MeeniMc** [comment] 2023-09-20 02:28
Try downgrading Fabric API from 0.89 to 0.88

**Comment by NoltoxGit** [comment] 2023-09-20 20:11
Hello @lukas27892 & @iofloodMichael,

You can download the latest version of Indium compatible with Fabric API `0.89.0` [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar) !

**Comment by comp500** [comment] 2023-09-23 00:18
Duplicate of #232

**Closed as not planned by comp500** 2023-09-23 00:18 UTC
