### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mindryder** [comp500/Indium#233] opened 2023-09-19 01:58 UTC
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-09-19 04:56:21
Description: Tessellating block in world - Indium Renderer

java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.TerrainRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at io.github.fabricators_of_create.porting_lib.models.RenderMaterialModel.emitBlockQuads(RenderMaterialModel.java:34)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$emc000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)

-- Block being tessellated --
Details:
	Block: Block{regions_unexplored:fireweed}
	Block location: World: (-482,64,224), Section: (at 14,0,0 in -31,4,14; chunk contains blocks -496,-64,224 to -481,319,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
Stacktrace:
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$emc000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Block being rendered --
Details:
	Block: Block{regions_unexplored:fireweed}
	Block location: World: (-482,64,224), Section: (at 14,0,0 in -31,4,14; chunk contains blocks -496,-64,224 to -481,319,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Chunk section: RenderSection at chunk (-31, 4, 14) from (-496, 64, 224) to (-481, 79, 239)
	Render context volume: class_3341{minX=-498, minY=62, minZ=222, maxX=-479, maxY=81, maxZ=241}
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_746['MindRyder'/253, l='ClientLevel', x=-501.17, y=63.00, z=231.14]]
	Chunk stats: 1024, 115
	Level dimension: minecraft:overworld
	Level spawn location: World: (-36,69,-15), Section: (at 12,5,1 in -3,4,-1; chunk contains blocks -48,-64,-16 to -33,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 99874939 game time, 260811 day time
	Server brand: TENDERLYMAFIA
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at pro.gravit.launcher.tENderlyMAFiaA.tenDErLyMAfiA2(Unknown Source)
	at pro.gravit.launcher.tENderlyMAFiaA.main(Unknown Source)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, minecraft:supporteatinganimation, visualoverhaul:rounddiscs, betterbeds:connectedbeds, betterbeds:fancybeds, betterbeds:fancyconnectedbeds, visualoverhaul:coloredwaterbucket, visualoverhaul:fancyfurnace, visualoverhaul:nobrewingbottles, black_icons, file/§fAnimated §cR§aG§9B §fInv. GUI 1.20.0.zip, minecraft:udsupporteatinganimation, file/§6§lClassic 3D v15.2.zip, file/Better+Lanterns+v1.1.2.zip, file/BetterLeavesAdd-onV3.0-1.20.zip, vinery:bushy_leaves, file/FreshAnimations_v1.8.1.zip, file/TenderlyMafiaFontFix.zip, Moonlight Mods Dynamic Assets

**Comment by some-du6e** [comment] 2023-09-20 03:01
same https://paste.atlauncher.com/view/0ad3b9e4-30c1-4058-b8ac-d55f857a15e4

**Comment by NoltoxGit** [comment] 2023-09-20 20:08
Hello @mindryder & @some-du6e,

You can download the latest version of Indium compatible with Fabric API `0.89.0` [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar) !

**Comment by comp500** [comment] 2023-09-23 00:18
Duplicate of #232

**Closed as not planned by comp500** 2023-09-23 00:18 UTC
