### ISSUE TITLE
Indium causes crash upon joining world

### ISSUE THREAD

**Issue by fritofficial** [comp500/Indium#334] opened 2024-08-14 12:36 UTC
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

Upon joining world, minecraft exit with "-1" code. Joining without using Indium doesnt lead up to crash. Using indium before 14th august worked without crashing

### Steps to Reproduce

1. Have Indium and Sodium
2. Open Minecraft
3. Join world

### Mod Version

1.0.34

### Minecraft Version

1.21

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/16612933/latest.log)

### Attach Crash Report

[crash-2024-08-14_17.26.32-client.txt](https://github.com/user-attachments/files/16612945/crash-2024-08-14_17.26.32-client.txt)

### Additional Information

java 21.0.3 2024-04-16 LTS (java --version)

Fabric Loader ver. 0.16.0
Sodium ver. 0.5.11
Fabric API ver. 0.102.0
Fabric API, Indium and Sodium downloaded at 14.08.2024 using Modrith

**Comment by dmstewart42** [comment] 2024-08-14 17:28
another #324

**Comment by IanNubbit** [comment] 2024-08-14 21:28
Just twiddling our thumbs waiting for this to be updated to be compatible with up to date Fabric firmware...

**Comment by comp500** [comment] 2024-08-15 16:51
Duplicate of #324

**Closed as not planned by comp500** 2024-08-15 16:51 UTC
Labels: bug
