### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by brunomaisdivertido** [comp500/Indium#331] opened 2024-08-12 20:56 UTC
### Confirmation

- [ ] I have tested the bug without Sodium and Indium.
- [ ] I have kept all my mods up to date.

### Bug Description

What do I need to do to use the mod in minecraft 1.21.1?

### Minecraft Version

Minecraft 1.21.1

**Comment by IanNubbit** [comment] 2024-08-15 11:33
As of right now I believe there is no way. Indium works on fabric 100.8. but 100.8 does not support 1.21.1

**Comment by comp500** [comment] 2024-08-15 16:50
Duplicate of #324

**Closed as not planned by comp500** 2024-08-15 16:50 UTC
Labels: bug
