### ISSUE TITLE
crash with continuity 

### ISSUE THREAD

**Issue by lipoutou34** [comp500/Indium#237] opened 2023-09-20 13:56 UTC
the world loading is crashing when continuity is enabled
(with indium 1.0.26, sodium 0.5.3, and continuity 3.0.0-beta.3

where is the logs : https://mclo.gs/1VXrzjr

**Comment by FormulaAbyss** [comment] 2023-09-20 15:46
Indium only supports Sodium 0.5.2 as of writing this reply.

**Comment by NoltoxGit** [comment] 2023-09-20 20:06
> the world loading is crashing when continuity is enabled (with indium 1.0.26, sodium 0.5.3, and continuity 3.0.0-beta.3
> 
> where is the logs : https://mclo.gs/1VXrzjr

Hello,
Try to update your Fabric API mod and try to set rhis new build of Indium [here](https://github.com/NoltoxGit/Indium/releases/download/1.0.26.1%2Bmc1.20.1/indium-1.0.26-dev+mc1.20.1.jar) !

**Comment by YukiAyase** [comment] 2023-09-21 01:14
> the world loading is crashing when continuity is enabled (with indium 1.0.26, sodium 0.5.3, and continuity 3.0.0-beta.3
> 
> where is the logs : https://mclo.gs/1VXrzjr

Downgrade Fabric API to 0.88.1
Indium is currently incompatible with Fabric API 0.89.0

**Comment by comp500** [comment] 2023-09-23 00:19
Duplicate of #232

**Closed as not planned by comp500** 2023-09-23 00:19 UTC
