### ISSUE TITLE
Crashes game when loading into world

### ISSUE THREAD

**Issue by PotatoezMen-PotatoPixle** [comp500/Indium#327] opened 2024-08-07 20:39 UTC
### Confirmation

- [ ] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

Indium crashes game when 'Continuity' or 'Snow! Real Magic!' is loaded

### Steps to Reproduce

1. have indium (obviously) 2. have either 'Continuity' or 'Snow! Real Magic!' 3. load into world

### Mod Version

Indium 1.0.34

### Minecraft Version

1.21

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/16533976/latest.log)

### Attach Crash Report

[crash-2024-08-07_15.38.44-client.txt](https://github.com/user-attachments/files/16533996/crash-2024-08-07_15.38.44-client.txt)

**Comment by stumper66** [comment] 2024-08-08 13:45
I've been running into this also. The crash occurs if a version of Fabric API newer than 0.100.8+1.21 is installed.
You can stop the crashes by downgrading to Fabric API version 0.100.8+1.21.
This looks to be the culprit:
```
Description: Tessellating block in world - Indium Renderer

java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bmh000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:1570)```

![image](https://github.com/user-attachments/assets/72469b70-598f-47dc-86e9-19f927566268)

**Comment by Athar42** [comment] 2024-08-08 17:20
Just a little bump, as the update of the Fabric API is needed to run the newly 1.21.1, this will need to be addressed anyway 😋 (just posting there if anyone search for 1.21.1 issue :) )

**Comment by agaertner** [comment] 2024-08-09 22:16
Same thing. I already got the latest Fabric API version and am crashing with the same stacktrace as above.

**Comment by SpokenWig620933** [comment] 2024-08-10 11:19
Duplicate of #324

**Comment by alexia8225** [comment] 2024-08-11 01:51
> I've been running into this also. The crash occurs if a version of Fabric API newer than 0.100.8+1.21 is installed. You can stop the crashes by downgrading to Fabric API version 0.100.8+1.21. This looks to be the culprit:
> 
> ```
> Description: Tessellating block in world - Indium Renderer
> 
> java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
> 	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
> 	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
> 	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
> 	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
> 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bmh000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
> 	at java.base/java.lang.Thread.run(Thread.java:1570)```
> 
> ![image](https://github.com/user-attachments/assets/72469b70-598f-47dc-86e9-19f927566268)
> ```

Soo this just saved me after a day of research and thinking "Snow! Real Magic!" was the culprit! Downgrading to Fabric API version 0.100.8+1.21 saved me! Thank you so much. Now to delete my issue to Snownee lol :,)

**Comment by No-Eul** [comment] 2024-08-13 07:20
> I've been running into this also. The crash occurs if a version of Fabric API newer than 0.100.8+1.21 is installed. You can stop the crashes by downgrading to Fabric API version 0.100.8+1.21. This looks to be the culprit:
> 
> ```
> Description: Tessellating block in world - Indium Renderer
> 
> java.lang.NoSuchMethodError: 'void net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(net.minecraft.class_1087, net.minecraft.class_2680, java.util.function.Supplier, net.fabricmc.fabric.api.renderer.v1.render.RenderContext, net.fabricmc.fabric.api.renderer.v1.mesh.QuadEmitter)'
> 	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039)
> 	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
> 	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
> 	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
> 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bmh000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
> 	at java.base/java.lang.Thread.run(Thread.java:1570)```
> 
> ![image](https://github.com/user-attachments/assets/72469b70-598f-47dc-86e9-19f927566268)
> ```

Fabric API 0.102.0+1.21 works well without the crash for me.

**Comment by comp500** [comment] 2024-08-15 16:49
Duplicate of #324

**Closed as not planned by comp500** 2024-08-15 16:49 UTC
Labels: bug
