### ISSUE TITLE
Minecraft crashes every time I load a world.

### ISSUE THREAD

**Issue by Losyash01** [comp500/Indium#336] opened 2024-08-15 08:28 UTC
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

I installed the continuity mod in conjunction with indium, I turned on the mod resource pack. I entered the world and the game froze while loading the territory. When I click the mouse a couple of times, Windows says that jdk is not responding
Mods: fabric api, sodium, continuity, indium.

### Mod Version

1.0.34

### Minecraft Version

1.21

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/16623157/latest.log)

### Attach Crash Report

[crash-2024-08-15_11.11.05-client.txt](https://github.com/user-attachments/files/16623162/crash-2024-08-15_11.11.05-client.txt)

### Additional Information

Crashes only occur if resource packs that add texture connections are connected

**Comment by IanNubbit** [comment] 2024-08-15 11:32
another #324

**Comment by neptunecentury** [comment] 2024-08-15 13:28
This is happening to me too. Do you have Fabric API version 0.102.0+1.21? If so, roll back to previous fabric api release version. I think there is a breaking change in Fabric API causing this.

**Comment by comp500** [comment] 2024-08-15 16:51
Duplicate of #324

**Closed as not planned by comp500** 2024-08-15 16:51 UTC
Labels: bug
