### ISSUE TITLE
Invisible Chunks/Blocks While Using Texturepack

### ISSUE THREAD

**Issue by im-h** [comp500/Indium#206] opened 2023-07-03 13:50 UTC
Some Chunks/Blocks are invisible on 1.0.18 while using a texturepack that has custom blocks but everything seems fine on 1.0.15

Indium 1.0.18:
![2023-07-03_15 30 16](https://github.com/comp500/Indium/assets/138497029/9b65c0d9-9b97-42f8-b30a-f9139b029593)
Indium 1.0.15:
![2023-07-03_15 33 04](https://github.com/comp500/Indium/assets/138497029/a9ad35d8-e404-45b4-ac36-6bc83e521001)

Version: 0.14.21-1.19.4
Mods:
<sub>3dskinlayers-fabric-1.5.3-mc1.19.4.jar
animatica-0.6+1.20.jar
appleskin-fabric-mc1.19.4-2.4.4.jar
architectury-8.1.87-fabric.jar
AxesAreWeapons-1.6.5-fabric-1.19.3.jar
balm-fabric-1.19.4-6.0.2.jar
bettermounthud-1.2.1.jar
BetterThirdPerson-Fabric-1.19-1.9.0.jar
capes-1.5.3+1.19.4-fabric.jar
cardinal-components-api-5.1.0.jar
charmofundying-fabric-6.3.0+1.19.4.jar
CITResewn-1.1.3+1.19.4.jar
clientcommands-2.7.13.jar
clienttweaks-fabric-1.19.4-10.0.2.jar
cloth-config-10.0.96-fabric.jar
complete-bone-meal-2.1.0+1.19.4.jar
completeconfig-2.3.1.jar
continuity-3.0.0-beta.2+1.19.3.jar
Controlling-fabric-1.19.4-11.1.5.jar
dcch-1.3.jar
DiagonalFences-v6.0.0-1.19.4-Fabric.jar
durabilitytooltip-1.1.4a-fabric-mc1.19.jar
dynamic-fps-2.2.0.jar
easiervillagertrading-1.19.3-fabric0.68.1-1.5.4.jar
EasyAnvils-v6.0.0-1.19.4-Fabric.jar
EasyMagic-v6.0.0-1.19.4-Fabric.jar
EasyShulkerBoxes-v6.0.0-1.19.4-Fabric.jar
eating-animation-1.9.3.jar
elytraslot-fabric-6.2.1+1.19.4.jar
entityculling-fabric-1.6.2-mc1.19.4.jar
entity_model_features_fabric_1.19.4-0.2.9.jar
entity_texture_features_fabric_1.19.4-4.4.4.jar
fabric-api-0.84.0+1.19.4.jar
fabric-carpet-1.19.4-1.4.101+v230319.jar
fabric-language-kotlin-1.9.6+kotlin.1.8.22.jar
fabric-release-regrowth-1.19.4-31.1.0.jar
fabrication-3.3.1+1.19.4.jar
FallingTree-1.19.4-3.12.2.jar
Female-Gender-Mod-fabric-1.19.4-3.0.1.jar
ferritecore-5.2.0-fabric.jar
figura-0.1.0+1.19.4.jar
fiveonefouroneeight-1.0.0.jar
ForgeConfigAPIPort-v6.0.2-1.19.4-Fabric.jar
indium-1.0.15+mc1.19.4.jar
interactic-0.2.0+1.19.4.jar
iris-mc1.19.4-1.6.4.jar
Jade-1.19.4-fabric-10.3.1.jar
jamlib-0.6.0+1.19.4.jar
jei-1.19.4-fabric-13.1.0.15.jar
journeymap-1.19.4-5.9.7-fabric.jar
JustEnoughResources-Fabric-1.19.4-1.3.3.219.jar
KnowMyName-1.2.0-dev.jar
krypton-0.2.2.jar
lambdynamiclights-2.3.1+1.19.4.jar
language-reload-1.5.8+1.19.4.jar
lazydfu-0.1.3.jar
LetSleepingDogsLie-1.19.3-4-1.1.1.jar
litematica-fabric-1.19.4-0.14.3.jar
lithium-fabric-mc1.19.4-0.11.1.jar
malilib-fabric-1.19.4-0.15.4.jar
microdurability-0.3.6+1.19.4.jar
midnightlib-fabric-1.3.0.jar
minihud-fabric-1.19.4-0.26.2.jar
mixintrace-1.1.1+1.17.jar
modelfix-1.10-fabric.jar
modmenu-6.2.3.jar
morechathistory-1.19.1-1.1.1.jar
MouseTweaks-fabric-mc1.19.4-2.24.jar
mousewheelie-1.11.1+mc1.19.4.jar
no-telemetry-1.7.0.jar
notenoughanimations-fabric-1.6.4-mc1.19.4.jar
optigui-2.1.2.jar
owo-lib-0.10.6+1.19.4.jar
PerspectiveModRedux-1.17-0.0.5_01.jar
PuzzlesLib-v6.0.11-1.19.4-Fabric.jar
reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar
right-click-harvest-3.2.2+1.19.x-1.20.1-fabric.jar
Searchables-fabric-1.19.4-1.0.3.jar
shulkerboxtooltip-fabric-3.4.0+1.19.4.jar
smoothboot-fabric-1.19.4-1.7.0.jar
sodium-extra-0.4.18+mc1.19.4-build.100.jar
sodium-fabric-mc1.19.4-0.4.10+build.24.jar
starlight-1.1.1+fabric.ae22326.jar
status-effect-bars-1.0.2.jar
supermartijn642configlib-1.1.6-fabric-mc1.19.jar
technomodel-1.0.4.jar
tooltipfix-1.1.1-1.19.3.jar
travelers-backpack-1.19.4-8.4.7.jar
trinkets-3.6.0.jar
tweakeroo-fabric-1.19.4-0.16.0.jar
VisualWorkbench-v6.0.1-1.19.4-Fabric.jar
waveycapes-fabric-1.4.0-mc1.19.3.jar
WI-Zoom-1.4-MC1.19.4.jar
yet-another-config-lib-forge-3.0.3+1.19.4.jar</sub>

**Comment by YukiAyase** [comment] 2023-07-05 03:00
This is not an Indium problem
**This is on Continuity's side and is already a known issue**

Currently the temporary solutions are downgrading Indium 1.0.15 or not using any emissive resource packs/turning off emissive textures in Continuity's setting if you're eager to use the latest version of Indium

Edit: Forgot to mention this issue, https://github.com/PepperCode1/Continuity/issues/253, also duplicate of https://github.com/comp500/Indium/issues/199

**Comment by comp500** [comment] 2023-07-10 15:38
Duplicate of #199

**Closed as not planned by comp500** 2023-07-10 15:38 UTC
