### ISSUE TITLE
please update indium to newer sodium versions...

### ISSUE THREAD

**Issue by szunakabeats** [comp500/Indium#276] opened 2024-02-02 22:18 UTC
as the title says. thx for your hard work !

**Comment by rakantoh** [comment] 2024-02-03 02:02
please, this mod is essential to use with sodium, update soon!

**Comment by papamaionise** [comment] 2024-02-03 18:44
please update

**Comment by EthanRStokes** [comment] 2024-02-03 22:39
duplicate of #271

**Comment by TobiasReindl** [comment] 2024-02-04 08:02
Indium is the last one that is missing now as Nvidium is also up to date with the newest Sodium and Iris version

**Comment by R00tB33rMan** [comment] 2024-02-05 03:47
> Indium is the last one that is missing now as Nvidium is also up to date with the newest Sodium and Iris version

Read my most recent comment in the issue report #271. It’ll fully resolve your issues.

**Closed as completed** 2024-02-05 20:56 UTC
