### ISSUE TITLE
[Quilt 1.20.1] crashes with origins++

### ISSUE THREAD

**Issue by glittermutt** [comp500/Indium#246] opened 2023-09-30 16:45 UTC
i have no idea whats happening here, PLEASEE help
[crash-2023-09-30_21.40.30-client.txt](https://github.com/comp500/Indium/files/12775145/crash-2023-09-30_21.40.30-client.txt)

**Comment by comp500** [comment] 2023-10-05 23:39
Your actual error is right at the bottom:
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#timeclock:timeclock-common.mixins.json:client.ModifyTickDeltaMixin$GameRendererMixin from mod timeclock] from phase [DEFAULT] in config [#timeclock:timeclock-common.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 29 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 4 for @ModifyArg is invalid for args (Lnet/minecraft/class_4184;Lnet/minecraft/class_1922;Lnet/minecraft/class_1297;ZZF), expected F on net/minecraft/class_757::setup [INJECT Applicator Phase -> #timeclock:timeclock-common.mixins.json:client.ModifyTickDeltaMixin$GameRendererMixin from mod timeclock -> Apply Injections ->  -> Inject -> #timeclock:timeclock-common.mixins.json:client.ModifyTickDeltaMixin$GameRendererMixin from mod timeclock->@ModifyArg::setup(F)F]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:158)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:113)
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82)
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:103)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
```

Looks like something to do with the `timeclock` mod, not Indium?

**Comment by comp500** [comment] 2023-10-14 12:37
Closing (doesn't seem to be caused by Indium)

**Closed as not planned by comp500** 2023-10-14 12:37 UTC
