### ISSUE TITLE
Minecraft Crashes every time I load a world

### ISSUE THREAD

**Issue by RelightOne** [comp500/Indium#333] opened 2024-08-14 09:57 UTC
### Confirmation

- [X] I have tested the bug without Sodium and Indium.
- [X] I have kept all my mods up to date.

### Bug Description

Whenever I open a world with indium installed it immediately crashes, I have no idea why

### Steps to Reproduce

1. Open Minecraft with Sodium and Indium installed on 1.21
2. Have any resource pack installed
3. Open a world

### Mod Version

1.0.34

### Minecraft Version

1.21

### Attach latest.log

[latest.log](https://github.com/user-attachments/files/16611160/latest.log) 
Also its here: https://mclo.gs/KDbQgbh

### Attach Crash Report

[crash-2024-08-14_19.49.03-client.txt](https://github.com/user-attachments/files/16611153/crash-2024-08-14_19.49.03-client.txt)

**Comment by dmstewart42** [comment] 2024-08-14 17:26
#324

**Comment by comp500** [comment] 2024-08-15 16:51
Duplicate of #324

**Closed as not planned by comp500** 2024-08-15 16:51 UTC
Labels: bug
