### ISSUE TITLE
Indium doesn't turn on

### ISSUE THREAD

**Issue by Emeraldnickel** [comp500/Indium#58] opened 2021-05-11 22:51 UTC
Whenever I try to run the game with this mod, the console returns this message:
[Indigo] Different rendering plugin detected; not applying Indigo.
Unfortunately, one of the mods in the pack I'm building requires Indium and therefore I can't load worlds. How do I get Indium to turn on?

**Comment by comp500** [comment] 2021-05-11 23:01
That message is normal; Indium is not Indigo, Indigo is supplied as part of Fabric API. Both Indium and Sodium stop Indigo from running, as it does not work with Sodium.

**Comment by Emeraldnickel** [comment] 2021-05-11 23:06
Wait, that means I have a different problem then... Do I open another issue or keep it here

**Comment by comp500** [comment] 2021-05-12 03:34
Might as well keep it here... please send the crash report or log for the issue you're having!

**Comment by Emeraldnickel** [comment] 2021-05-12 04:33
I've had a few different ones, somehow. Here's the first one with all fresh installs:
[crash-2021-05-11_19.00.50-client.txt](https://github.com/comp500/Indium/files/6463443/crash-2021-05-11_19.00.50-client.txt)
And here's one with a modified config file (which may have broken it more? I'm not sure)
[crash-2021-05-12_09.23.21-client.txt](https://github.com/comp500/Indium/files/6463446/crash-2021-05-12_09.23.21-client.txt)

**Comment by comp500** [comment] 2021-05-13 22:29
Both these crashes seem to be unrelated to Indium - the first is from Immersive Portals (which does need a specific Sodium fork to work) and the second is from Visual Overhaul. Definitely try removing Sodium and Indium when you get a crash to see if the crash is caused by them, or is unrelated.

**Comment by Emeraldnickel** [comment] 2021-05-13 22:33
Removed both and it works now! Thanks for the help but we had the right fork (the /next one). Any idea why it crashed?

**Comment by comp500** [comment] 2021-05-14 00:20
Assuming you removed Immersive Portals and Visual Overhaul, I don't really know, I'd suggest asking their respective support channels (Immersive Portals has a discord server). The Visual Overhaul crash looks like it could be related to Immersive Portals, as it tries to use the player entity on client tick but there isn't any (presumably this is from ticking the Immersive Portals loaded world).

**Comment by comp500** [comment] 2021-06-22 22:15
Closing as this seems to be unrelated.

**Closed by comp500** 2021-06-22 22:15 UTC
