### ISSUE TITLE
[URGENT] [BUG] Could not execute entrypoint stage 'client' due to errors, provided by 'indium'!

### ISSUE THREAD

**Issue by NopeProsOnly** [comp500/Indium#193] opened 2023-05-16 12:39 UTC
https://paste.gg/p/anonymous/b1b992284db54034a645203168a68b38

The launcher has updated. With that update, they made accessibility settings more accessible. This means that the first screen you see isn't the main menu. I don't know if this is related, but may help.

**Comment by comp500** [comment] 2023-05-16 23:49
This is completely unrelated to Indium:

> Mixin transformation of net.minecraft.client.render.GameRenderer failed
> ...
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector injected(Lnet/minecraft/GameRenderer;)V in reimaginedmenus.mixins.json:GameRendererMixin from mod reimaginedmenus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reimaginedmenus-refmap.json

Report this crash to the developer of Reimagined World Menu.

**Comment by NopeProsOnly** [comment] 2023-05-17 00:05
So, reimaginedworldmenu cause an error with indium? Meaning this mod was involved but not the cause?

**Comment by comp500** [comment] 2023-05-17 00:08
The crash stacktrace is saying that Indium tried to load Minecraft's GameRenderer class, and that `reimaginedmenus` failed to apply it's modifications to the Minecraft GameRenderer code. It's possible that this is caused by a conflict with Indium or Sodium, but from a brief look at the code I can't see an obvious reason why this would occur. Try running the game without Sodium or Indium to determine if Reimagined World Menu is conflicting with them.

**Comment by comp500** [comment] 2023-06-04 13:32
Closing: assumed to not be an Indium issue (please report to the author of Reimagined World Menu)

**Closed as not planned by comp500** 2023-06-04 13:32 UTC
