### ISSUE TITLE
Crashing on start of game

### ISSUE THREAD

**Issue by crystalidk** [comp500/Indium#128] opened 2022-07-13 21:41 UTC
no idea what the problem is but heres my crash log if you wanna look at it
| | |
vvv
[here](https://pastebin.com/KFZP5MA7)

**Comment by comp500** [comment] 2022-07-15 20:03
Please read the crash log! (duplicate of https://github.com/comp500/Indium/issues/97)

```
Failed to load Indium: Indium is not currently compatible with FREX 6.x, as it provides an incompatible implementation of the Fabric Rendering API; the FREX API may be directly supported in future.
  FREX is bundled as part of JSON Model Extensions
```

**Closed as not planned by comp500** 2022-07-15 20:03 UTC
